# Generated by Django 6.0.4 on 2026-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_clip',
            field=models.FileField(blank=True, null=True, upload_to='videos/previews/'),
        ),
    ]
